baseURL = 'https://alex-dev.me/'
languageCode = 'en-us'
paginate = 5
theme = "terminal"

[params]
  contentTypeName = "index"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = true
  enableGitInfo = true
  autoCover = true

[languages]
  [languages.en]
    title = "Alex"
    subtitle = "Alex"
    keywords = "Web development"
    copyright = "Alex"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Alex"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"